In [32]:
import numpy as np
arr = np.random.randint(1,100, size = (10,5))
# print(arr)
# print(arr.shape)

shaped_arr = arr.reshape(5,10) #shape change korar jonno reshabe use hoi ,,,amat given data sara posible na
print(shaped_arr)


# flatten = shaped_arr.flatten() #1D tea convert korar jonno but it make row wise
# print(flatten)
# flatten.ndim

column_wise_flattining = np.ravel(shaped_arr , order = 'F') #1D tea convert korar jonno but it make column wise
print(column_wise_flattining)
row_wise_flattining = np.ravel(shaped_arr , order = 'C') #'C Dea column ' and 'F' dea row wise flattening no need
print(column_wise_flattining)

[[44 24 86 98 21 65 64 20 15 13]
 [27 77 68 15 46 31 25 10 92 97]
 [37 77 11 90 49 88 74 41 84  4]
 [25 55 25 85 16 61 62 89 72 79]
 [25 23 94 43 18 75 46 81 91 40]]
[44 27 37 25 25 24 77 77 55 23 86 68 11 25 94 98 15 90 85 43 21 46 49 16
 18 65 31 88 61 75 64 25 74 62 46 20 10 41 89 81 15 92 84 72 91 13 97  4
 79 40]
[44 27 37 25 25 24 77 77 55 23 86 68 11 25 94 98 15 90 85 43 21 46 49 16
 18 65 31 88 61 75 64 25 74 62 46 20 10 41 89 81 15 92 84 72 91 13 97  4
 79 40]


## Concatenant

In [38]:
a = np.random.randint(1,10 , size = (2,3))
b = np.random.randint(20,30 , size = (2,3))
print(a)
print(b)

[[6 1 4]
 [2 6 1]]
[[20 20 25]
 [28 23 24]]


In [41]:
con_row = np.concatenate((a, b), axis=0)
print(con_row)
print("\n")
con_col = np.concatenate((a, b), axis=1)
print(con_col)

[[ 6  1  4]
 [ 2  6  1]
 [20 20 25]
 [28 23 24]]


[[ 6  1  4 20 20 25]
 [ 2  6  1 28 23 24]]


In [43]:
#error
# Two arrays with same number of columns (3) → can stack vertically
a = np.array([[1, 2, 3],
              [4, 5, 6]])  #chailea random row col gnerate korea neya jai

b = np.array([[7, 8, 9]])

vertical = np.concatenate((a, b), axis=0)  # Row-wise
print("Vertical:\n", vertical)

horizontal = np.concatenate((a, b), axis=1)  # Column-wise
print("Horizontal:\n", horizontal)
#Aikhan a error howa thik aca

Vertical:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [46]:
#Transpose Matrix
mat = np.array([[12,20,30],
               [22,34,73]])
transpose = mat.T
print(transpose)

[[12 22]
 [20 34]
 [30 73]]


In [54]:
#array Split

a = np.random.randint(1,10 , size = (9))
splited_array = np.array_split(a,3)
print(a)
print(splited_array)

[2 1 2 4 6 7 4 8 5]
[array([2, 1, 2], dtype=int32), array([4, 6, 7], dtype=int32), array([4, 8, 5], dtype=int32)]


## arithmetic operator and math function

In [76]:
#faster for vectorization
x = np.array([10,20,30,100])
y = np.array([2,3,4,5])

add = x+y
print("Addition is",add)

sub = x-y
print("subtraction is",sub)

mul = x*y
print("multiplictaion is",mul)

div = x/y
print("Dividion is",div)

reminder = x%y
print("reminder is",reminder)

Addition is [ 12  23  34 105]
subtraction is [ 8 17 26 95]
multiplictaion is [ 20  60 120 500]
Dividion is [ 5.          6.66666667  7.5        20.        ]
reminder is [0 2 2 0]


In [71]:
#Math Function for trigonometric

#sim , cos , tan take value in radian

sin_val=np.sin(x)
print(sin_val)
cos_val=np.cos(x)
print(cos_val)
tan_val=np.tan(x)
print(tan_val)

#radient to Degree convertion 
deg_con = np.rad2deg(x)
print("radient to Degree convertion ",deg_con)
#Degree to radient convertion

deg_con = np.deg2rad(x)
print("Degree to radient convertion ",deg_con)

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493]
radient to Degree convertion  [ 572.95779513 1145.91559026 1718.87338539 2291.83118052]
Degree to radient convertion  [0.17453293 0.34906585 0.52359878 0.6981317 ]


In [92]:
#Log
x = np.array([10,20,16,100])

div_by_log_with_anything = np.log10(x) #log10 means 10 dea koto bar vag kora jabea
print(div_by_log_with_anything)

#square root/borgo Mul
sqrt = np.sqrt(x)
print(sqrt)

#akta por r akta +
cbcb = np.cumulative_sum(x)
print(cbcb)

# Cumulative Sum
# 1
# 1 + 2 = 3
# 1 + 2 + 3 = 6
# 1 + 2 + 3 + 6 = 10


[1.         1.30103    1.20411998 2.        ]
[ 3.16227766  4.47213595  4.         10.        ]
[ 10  30  46 146]


## logical Function

In [95]:
x = np.array([10,20,30,100])
y = np.array([2,3,4,5])

grater_then = x > y
print(grater_then)

les_then = x < y
print(les_then)

equal_to = x == y
print(equal_to)

not_equal_to = x != y
print(not_equal_to)





[ True  True  True  True]
[False False False False]
[False False False False]
[ True  True  True  True]


## Shorting

In [101]:
#inplace
x = np.array([1,53,12,80,234]) 
z= x.copy() #next dorkar na holea
print(z)
z.sort() 
print(z)

[  1  53  12  80 234]
[  1  12  53  80 234]


In [99]:
#copy sorting
print(x)
copy_sort = np.sort(x) #next dorkar holea
print(copy_sort)
print(x)

[  1  53  12  80 234]
[  1  12  53  80 234]
[  1  53  12  80 234]


In [105]:
#2d array sorting
#horizontal axis = 1
mat = np.array([ [3,6,3],
                  [1,4,2] 
                ])
print(mat)
print("\n")
print("\n")
horizontal_sort = np.sort(mat,axis=1)
print(horizontal_sort)

vertical_sort = np.sort(mat,axis=0)
print(vertical_sort)

[[3 6 3]
 [1 4 2]]




[[3 3 6]
 [1 2 4]]
[[1 4 2]
 [3 6 3]]


## Searching 

In [110]:
print(x)

index = np.where(x==12)
print(index)

index = np.where(x<8,x,0) #8 er thakea soto value gilo k 0 bananor jonno 
print(index)


[  1  53  12  80 234]
(array([2]),)
[1 0 0 0 0]


In [119]:
print(mat)
index = np.where(mat>3)
print(index)

arr = np.where(mat<=3,mat,0) #3 er thakea soto value gilo k 0 bananor jonno 
print(arr)

[[3 6 3]
 [1 4 2]]
(array([0, 1]), array([1, 1]))
[[3 0 3]
 [1 0 2]]


In [121]:
print(x)
max_value = np.argmax(x) # Boro value ta ber korar jonno jodi max value same 2/3 ta tahkea taholea ager ta print hba
print(max_value)
min_value = np.argmin(x) 
print(min_value)

[  1  53  12  80 234]
4
0


## Counting

In [142]:
a = np.random.randint(1,100 , size=(100))
print(a)
print("\n")

find_value = np.count_nonzero(a>80) #boro koita aca
print(find_value)

print("\n")
find_value = np.count_nonzero(a == 14) #koibar aca
print(find_value)
print("\n")


unique_value = np.unique(a)
print(unique_value)
print("\n")

unique_value = np.unique(a,return_counts = True)
print(unique_value)                        

[77  6 79 62 18 47 42 42 63 42 56 95 25 22 40 46 41 61 38 61 58 54 66 87
 18 41 80 50 81 76 37 76 24 44 44 99 77 54 23 86 22 55 68 10 43 13  3 77
 24  9 72 24 92 27 82 28 40 77 44 17 10 48 82 60 41  8 53  4 66 30 39 17
 87 52 71 32 59 39  8 47 90 29 18 19 92 17 35 42 41 85 38 54 99  1 68 32
 23 57 22 96]


14


0


[ 1  3  4  6  8  9 10 13 17 18 19 22 23 24 25 27 28 29 30 32 35 37 38 39
 40 41 42 43 44 46 47 48 50 52 53 54 55 56 57 58 59 60 61 62 63 66 68 71
 72 76 77 79 80 81 82 85 86 87 90 92 95 96 99]


(array([ 1,  3,  4,  6,  8,  9, 10, 13, 17, 18, 19, 22, 23, 24, 25, 27, 28,
       29, 30, 32, 35, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 50, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 66, 68, 71, 72, 76, 77,
       79, 80, 81, 82, 85, 86, 87, 90, 92, 95, 96, 99], dtype=int32), array([1, 1, 1, 1, 2, 1, 2, 1, 3, 3, 1, 3, 2, 3, 1, 1, 1, 1, 1, 2, 1, 1,
       2, 2, 2, 4, 4, 1, 3, 1, 2, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 2, 2, 1, 1, 2, 4, 1, 1, 1, 2, 1, 1, 

## Statistical function

In [151]:
#data load

data = np.genfromtxt('student_scores.csv' , delimiter=',',skip_header=skip)

print(data)


# statistics
math_marks = data[::,:1]

print(math_marks.T) #T dilea row wise dekhar jonno

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks) # avg ber korar jonno
print(average_math_marks)

median_math_marks = np.median(math_marks) #middle er mark ta ber korar jonno
print(median_math_marks)

# standard deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)




NameError: name 'skip' is not defined

In [155]:

study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

correlation = np.corrcoef(data)
print("correlation Matrix:\n", correlation)

correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


## Linear Algebra

In [160]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# A and , B er row same hotea hba 
dot_product = np.dot(A,B)
print(dot_product)



print(np.trace(B)) #trace holo Diagonal borabora + kora




[[ 58  64]
 [139 154]]
17


In [161]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])

det_of_sq = np.linalg.det(sq_mat) # determinent ber korar jonno
print(det_of_sq)


rank_sq = np.linalg.matrix_rank(sq_mat) #rank ber korar jonno
print(rank_sq)


-9.51619735392994e-16


In [166]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product = np.dot(A,B)
print(dot_product)

[[19 22]
 [43 50]]


## Problem-1

In [14]:
one_d_array = np.array([10,20,30,40])
print("1D",one_d_array)
print(one_d_array.shape)
print(one_d_array.ndim)
print("\n")
two_d_array = np.array([
                    [11,22,33,44],
                    [1,2,3,4]
                            ])
print(two_d_array)
print(two_d_array.shape)
print(two_d_array.ndim)
print("\n")

three_d_array = np.array([
                     [ [11,22,33,44] ],
                      [ [1,2,3,4] ],
                       [ [1112,222,333,444] ]
                                            ])
# print(three_d_array)
print(three_d_array.shape)
print(three_d_array.ndim)



1D [10 20 30 40]
(4,)
1


[[11 22 33 44]
 [ 1  2  3  4]]
(2, 4)
2


(3, 1, 4)
3


## Problem - 2 

In [20]:
arr = np.zeros((3,3))
print(arr)
print("\n")
arr2 = np.ones((2,5))
print(arr2)
print("\n")
arr3 = np.full((4,4),7)
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


## Problem-3

In [47]:
arr = np.random.randint(0,15, (4,4))
print(arr)

print(arr[0]) #row print korar jonno 
print(arr[:,-1])

[[ 4  3  6  0]
 [ 2  9 13  8]
 [ 9 12 10 10]
 [ 4 12  8 12]]
[4 3 6 0]
[ 0  8 10 12]


## Problem - 4

In [52]:
arr = np.arange(10,51,2)
new_arr = arr
print(new_arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
