### NDarray

In [60]:
import numpy as np

#1D array

arr1 = np.array([1,2,3,4,5,])
print(arr1)
print(type(arr1))

print(arr1.ndim) #koto dimentional a aca ta dekhar jonno



#2d array
arr2 = np.array([ [1,2,3],
                  [4,5,6] 
                ])
print(arr2.ndim)


# 3D array

arr3 = np.array([ 
            [     [1,2,3],#floor 1
                  [4,5,6] ],

            [     [1,2,3],#Floor 2
                  [4,5,6] ],
            [     [1,2,3],#Floor 3
                  [4,5,6] ]
                ])

print(arr3.ndim)
print(arr3)

[1 2 3 4 5]


### Array attrubutes

In [8]:
#Dimention Check
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print("\n")

#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print("\n")

#Data Type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print("\n")

#size
print(arr1.size)
print(arr2.size)
print(arr3.size)


1
2
3


(5,)
(2, 3)
(3, 2, 3)


int64
int64
int64


5
6
18


### ndarray DataType

In [9]:
arr = np.array([1,2,3,])
print(arr.dtype)


arr = np.array([1.5,2.7,3,])
print(arr.dtype)



int64
float64


In [12]:
arr = np.array([1.5,2,3,])
#upcasting to float
print(arr.dtype)

#upcasting string
arr = np.array([1.5,2,"Hello",])
print(arr.dtype)


float64
<U32


## Selecting data Type for and Array

In [15]:
arr = np.array([1,2,300], dtype = np.int16) #for change fDatype
print(arr.dtype)
print(arr)

int16
[  1   2 300]


In [21]:
arr = np.array([1,2,300])
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)

int64
[  1   2 300]


## ndArray creation from existing Data

In [29]:
#list
lst = ([10,20,30,40,40.5])
arr = np.array(lst, dtype=np.int32) #Data type ta cng korar jonno(dtype=np.int32)
 
# print(arr)
# print(type(arr))
# print(arr.dtype)

mixed_lst = ([10,20,True,10.5,'Hello'])
arr = np.array(mixed_lst)

# print(arr)
# print(type(arr))
# print(arr.dtype)


matrix = [ [1,2,3],
           [4,5,6] 
                ]
arr = np.array(matrix) #nd array tea convert cora
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [37]:
#Tuple
tp1 = (10,20,30)
arr = np.array(tp1, dtype=np.int32) #Type 1
print(arr.dtype)
                                      #Ai 2 vabea ndArray tea convert corea
arr = arr.astype(np.int16) #Type 2
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [45]:
#set
st = {10,20,30}
arr = np.array(list(st)) #Fisrt a list a convert kortea hba for set
# print(arr.dtype)
#                                       #Ai 2 vabea ndArray tea convert corea
arr = arr.astype(np.int16) #Type 2
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [51]:
#Dictionary
dc = {'a' : 10, 'b' : 20, 'c' : 30}
keys = dc.keys()
print(keys)
values = dc.values()
print(values)

items = dc.items()
print(items)


dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])


In [56]:

#keys to nd array
arr = np.array(list(keys))
print(arr)
# arr = arr.astype(np.int16)   
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [57]:
#Values To nd Array
arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [59]:
#items to nd array

arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


## Creating ndnarray from Screatch

In [72]:
#Zeros
arr = np.zeros((1,3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.zeros_like(arr3) #arr 3 er moto korea
print(arr)
print(arr.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [70]:
#np.one
arr = np.ones((3,4,3),dtype=np.int8)

 #arr 3 er moto korea
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int8
(3, 4, 3)
3
36


In [74]:
#np.empty for differen 
arr = np.empty((4,3),dtype=np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[97  0  0]
 [ 0 98  0]
 [ 0  0 99]
 [ 0  0  0]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
12


In [96]:
#np.full
arr = np.full((4,3),10) #10 deyar reason is matrix full korar jonno , anything deya kora jai, must be defined
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.full_like(arr3,10.5)
print(arr)
print(arr.shape)
print(arr.dtype)


[[[10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]]]
(3, 2, 3)
int64


## array Creatuion with random values

In [112]:
#np.random.randomint(shape)

arr = np.random.randint(1,10 , (2,3)) #(2,3) row and column 1,10 hole koto thakea koto nibo

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[7 6 8]
 [8 8 9]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [122]:
#np.random.uniform(shape) holo flote nebar jonno 

arr = np.random.uniform(50,100 , (4, 3,4)) #(2,3) row and column 50,100 hole koto thakea koto nibo

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[73.94660089 63.69768686 58.17079272 74.120776  ]
  [66.70186814 93.45997275 75.67319109 61.25148118]
  [57.08242725 95.33786816 53.32646721 51.47906342]]

 [[79.46934505 66.55688693 66.75765831 88.57360211]
  [98.6233946  95.86928888 56.0440334  62.50279014]
  [62.56813628 71.76189246 91.51078351 81.62724612]]

 [[77.06216614 89.75819848 60.35740066 97.66326328]
  [95.92261465 53.90479479 71.35931218 89.21110675]
  [61.79129321 93.68858971 64.8905696  98.14186721]]

 [[89.15072215 66.46274135 53.19542976 95.26898433]
  [69.63767466 65.69210826 64.78948101 95.81107905]
  [87.05496381 78.71573363 53.86328663 95.83404939]]]
<class 'numpy.ndarray'>
float64
(4, 3, 4)
3
48


## array creatioin with Range

In [130]:
#np.arange(start , end , step)
arr = np.arange(1,10,1)
mat = arr.reshape(3,3) #reshape is use for make matrix

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [168]:
#np.linear Space(start, end(last included) , koita pick korbea)
arr = np.linspace(0,10,5)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 0.   2.5  5.   7.5 10. ]
<class 'numpy.ndarray'>
float64
(5,)
1
5


In [137]:
#np.logspace(start,end,koita value nibo)

arr = np.logspace(0,4,5)
print(arr)


[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]


## creating Matrix for Linear Algebra


In [142]:
#diagonal_matrix
diagonal_matrix = np.diag([1,4,3])
print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0]
 [0 4 0]
 [0 0 3]]
(3, 3)


In [167]:
#Ideantity Matrix

ideantity_matrix = np.eye(4)
print(ideantity_matrix)
print(ideantity_matrix.shape)
print("\n")


mat = np.eye(3)
print(mat)
print("\n")

mat = np.eye(3,4,-1) # komano holea nicher sorbea
print(mat)
print("\n")
mat = np.eye(3,4,2) #Barano holea uporer dik sorbea
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




## indexing & slicing

In [61]:
arr1[4] =100
print(arr1[4])
print(arr1)

print(arr2)

arr2[0][2] = 69
print(arr2[0][2])
print(arr2)


100
[  1   2   3   4 100]
[[ 1  2 69]
 [ 4  5  6]]
69
[[ 1  2 69]
 [ 4  5  6]]


In [65]:
# slicing
# 1D array = [start : end : step]
print(arr1)
a = arr1[1:4:].copy()
arr1[1] = 2
print(arr1)
print(a)


[  1   2   3   4 100]
[  1   2   3   4 100]
[2 3 4]


In [3]:
#2D slicing 
# arr[ row_start : row_end : step , column_start : column_end : step ]

print(arr2)
#for taking row
rows = arr2[0:1 , ]
roww = arr2[1: , ]
print(rows)
print(roww)

#for taking column
col = arr2[::, 0:1]
col2 = arr2[::, 1:2]
print(col)
print(col2)


print(arr3)
print("\n")

portion = arr3[:: , 1:2]
print(portion)



NameError: name 'arr2' is not defined

## Advanced indexing

In [83]:
lst = np.array([12,20,30,40])
values = lst[[0,3,1]]  #aivabea holo kon kon index er value lagbe seta
print(values)

[12 40]


In [92]:
print(arr2)

print(arr2[[0,1],[1,2]]) #(0,1 holo row)(1,2 holo colum er value nibo) specific value print nebar jono with number


print(arr2[arr2>2]) #bool er help nea 2 er boro gulo ber kora


arr2[arr2> 2] = 0 #2 thakea jata boro tader 0 banano
print(arr2)



[[ 1  2 69]
 [ 4  5  6]]
[2 6]
[69  4  5  6]
[[1 2 0]
 [0 0 0]]


In [104]:
#iteration


arr = ([[10,20,30],
        [100,200,300]])


for i in np.nditer(arr):
    print(i)

(array(10), array(100))
(array(20), array(200))
(array(30), array(300))


## problem-1

In [5]:
#numpy import korea nitea hba
lst_temps = [10, 20, 30, 40] 
ava_veriable = np.array(lst_temps)
fahrenheit = ava_veriable * 1.8 + 32
print(fahrenheit)

[ 50.  68.  86. 104.]


## problem - 2

In [15]:
#numpy import kora lagbea
lst = [10,20,30,40]
athlete_lst = np.array(lst)
print(athlete_lst.size)
print(athlete_lst.shape)
print(athlete_lst.dtype)
new_lst = athlete_lst / 60
print(new_lst)

4
(4,)
int64
[0.16666667 0.33333333 0.5        0.66666667]
